### PR TITLE
Lobby commands

### PR DESCRIPTION
**Pull request by swansontec**
CLI commands to go with airbitz/airbitz-core-js#8. Tested and working with Augur, aside from certificate errors on the new info1.edgesecure.co endpoint. The browser is happy, so I'm guessing this is a node.js issue.

### CODE REVIEW

**Comment by swansontec** [comment]
It might be the TacoBell WiFi, which is messing with some SSL certs.

**Comment by swansontec** [comment]
Nope, still happens while tethering:

```
Account.fetchLobby { FetchError: request to https://info1.edgesecure.co:8444/v1/appIdInfo/net.augur.app failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/william/airbitz/airbitz-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://info1.edgesecure.co:8444/v1/appIdInfo/net.augur.app failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

**Comment by paullinator** [comment]
Hmm. I have the same problem with Postman to info1 but it works fine inside our react-native app and from a browser. I'm unsure why. Does it work in the RN CLI? That would mirror the environment of our app.

**Comment by swansontec** [comment]
I haven't tested RN CLI, but with `process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0'`, it does work. I will be pushing one more fix to the core branch, since your API endpoint uses different names than what I was expecting. It also just ignores any errors hitting this endpoint, so users will see the appId instead of getting an error.

**Pull request merged**
